import type {
  ProjectListItem,
  ProjectDetail,
  TimelineEvent,
} from "./types";

export const MOCK_PROJECTS: ProjectListItem[] = [
  {
    project_id: "P001",
    project_name: "Lone Star Campus I",
    state: "TX",
    region_or_rto: "ERCOT",
    modeled_primary_load_mw: 300,
    lifecycle_state: "monitoring_ready",
    risk_tier: "high",
    current_hazard: 0.08,
    deadline_probability: 0.24,
    data_quality_score: 81,
    latest_update_date: "2026-04-01",
    phase_count: 3,
  },
  {
    project_id: "P002",
    project_name: "Desert Ridge Hyperscale",
    state: "AZ",
    region_or_rto: "WECC",
    modeled_primary_load_mw: 480,
    lifecycle_state: "under_review",
    risk_tier: "elevated",
    current_hazard: 0.05,
    deadline_probability: 0.17,
    data_quality_score: 63,
    latest_update_date: "2026-03-15",
    phase_count: 2,
  },
  {
    project_id: "P003",
    project_name: "Appalachian Core DC",
    state: "VA",
    region_or_rto: "PJM",
    modeled_primary_load_mw: 620,
    lifecycle_state: "active_construction",
    risk_tier: "moderate",
    current_hazard: 0.03,
    deadline_probability: 0.09,
    data_quality_score: 91,
    latest_update_date: "2026-04-08",
    phase_count: 4,
  },
  {
    project_id: "P004",
    project_name: "Great Lakes Exchange",
    state: "OH",
    region_or_rto: "PJM",
    modeled_primary_load_mw: 310,
    lifecycle_state: "monitoring_ready",
    risk_tier: "high",
    current_hazard: 0.12,
    deadline_probability: 0.35,
    data_quality_score: 55,
    latest_update_date: "2026-02-20",
    phase_count: 2,
  },
  {
    project_id: "P005",
    project_name: "Cascade Ridge AI Cluster",
    state: "WA",
    region_or_rto: "WECC",
    modeled_primary_load_mw: 800,
    lifecycle_state: "under_review",
    risk_tier: "elevated",
    current_hazard: 0.06,
    deadline_probability: 0.19,
    data_quality_score: 74,
    latest_update_date: "2026-03-28",
    phase_count: 5,
  },
  {
    project_id: "P006",
    project_name: "Sunbelt Compute Park",
    state: "GA",
    region_or_rto: "SERC",
    modeled_primary_load_mw: 400,
    lifecycle_state: "delayed",
    risk_tier: "high",
    current_hazard: 0.15,
    deadline_probability: 0.41,
    data_quality_score: 68,
    latest_update_date: "2026-01-10",
    phase_count: 2,
  },
  {
    project_id: "P007",
    project_name: "Northern Plains Hub",
    state: "ND",
    region_or_rto: "MISO",
    modeled_primary_load_mw: 350,
    lifecycle_state: "monitoring_ready",
    risk_tier: "low",
    current_hazard: 0.02,
    deadline_probability: 0.06,
    data_quality_score: 88,
    latest_update_date: "2026-04-02",
    phase_count: 1,
  },
];

export const MOCK_PROJECT_DETAILS: Record<string, ProjectDetail> = {
  P001: {
    project_id: "P001",
    project_name: "Lone Star Campus I",
    state: "TX",
    region_or_rto: "ERCOT",
    utility: "Oncor Electric",
    modeled_primary_load_mw: 300,
    headline_load_mw: 320,
    optional_expansion_mw: 150,
    lifecycle_state: "monitoring_ready",
    risk_tier: "high",
    announce_date: "2025-07-15",
    data_quality_score: 81,
    latest_update_date: "2026-04-01",
    phases: [
      {
        phase_id: "PH1",
        phase_name: "Phase 1 — Initial Build",
        modeled_primary_load_mw: 100,
        optional_expansion_mw: 50,
        target_energization_date: "2026-09-01",
        status: "planning",
        utility: "Oncor Electric",
        interconnection_status_known: false,
        new_transmission_required: true,
      },
      {
        phase_id: "PH2",
        phase_name: "Phase 2 — Core Expansion",
        modeled_primary_load_mw: 120,
        optional_expansion_mw: 60,
        target_energization_date: "2027-03-01",
        status: "planning",
        utility: "Oncor Electric",
        interconnection_status_known: false,
        new_transmission_required: true,
      },
      {
        phase_id: "PH3",
        phase_name: "Phase 3 — Optional Wing",
        modeled_primary_load_mw: 80,
        optional_expansion_mw: 40,
        target_energization_date: "2027-09-01",
        status: "planning",
        utility: null,
        interconnection_status_known: false,
        new_transmission_required: false,
      },
    ],
    score: {
      project_id: "P001",
      phase_id: "PH1",
      current_hazard: 0.08,
      deadline_probability: 0.24,
      project_stress_score: 0.61,
      regional_stress_score: 0.54,
      anomaly_score: 0.33,
      evidence_quality_score: 0.74,
      top_drivers: [
        "New transmission required",
        "Power path not fully identified",
        "High electrical dependency complexity",
        "Utility large-load policy actions in ERCOT region",
      ],
      weak_signal_summary:
        "Two E2 power-linked disruption signals in trailing 4 quarters. One E4 workaround indicator (staged energization planned). Regional E3 utility action score elevated.",
      graph_fragility_summary: {
        most_likely_break_node: "transmission_upgrade",
        unresolved_critical_nodes: 3,
      },
      as_of_quarter: "2026-Q1",
    },
  },
  P002: {
    project_id: "P002",
    project_name: "Desert Ridge Hyperscale",
    state: "AZ",
    region_or_rto: "WECC",
    utility: "APS (Arizona Public Service)",
    modeled_primary_load_mw: 480,
    headline_load_mw: 500,
    optional_expansion_mw: 200,
    lifecycle_state: "under_review",
    risk_tier: "elevated",
    announce_date: "2025-09-01",
    data_quality_score: 63,
    latest_update_date: "2026-03-15",
    phases: [
      {
        phase_id: "PH1",
        phase_name: "Phase 1",
        modeled_primary_load_mw: 240,
        optional_expansion_mw: 100,
        target_energization_date: "2027-01-01",
        status: "permitting",
        utility: "APS (Arizona Public Service)",
        interconnection_status_known: true,
        new_transmission_required: false,
      },
      {
        phase_id: "PH2",
        phase_name: "Phase 2",
        modeled_primary_load_mw: 240,
        optional_expansion_mw: 100,
        target_energization_date: "2027-09-01",
        status: "planning",
        utility: "APS (Arizona Public Service)",
        interconnection_status_known: false,
        new_transmission_required: true,
      },
    ],
    score: {
      project_id: "P002",
      phase_id: "PH1",
      current_hazard: 0.05,
      deadline_probability: 0.17,
      project_stress_score: 0.42,
      regional_stress_score: 0.38,
      anomaly_score: 0.21,
      evidence_quality_score: 0.63,
      top_drivers: [
        "Large load concentration in WECC subregion",
        "Phase 2 transmission dependency unresolved",
        "Low evidence coverage trailing 2 quarters",
      ],
      weak_signal_summary:
        "One E2 signal (timeline slippage, permitting phase). No E4 workarounds detected.",
      graph_fragility_summary: {
        most_likely_break_node: "substation_upgrade",
        unresolved_critical_nodes: 1,
      },
      as_of_quarter: "2026-Q1",
    },
  },
  P003: {
    project_id: "P003",
    project_name: "Appalachian Core DC",
    state: "VA",
    region_or_rto: "PJM",
    utility: "Dominion Energy",
    modeled_primary_load_mw: 620,
    headline_load_mw: 650,
    optional_expansion_mw: null,
    lifecycle_state: "active_construction",
    risk_tier: "moderate",
    announce_date: "2024-11-01",
    data_quality_score: 91,
    latest_update_date: "2026-04-08",
    phases: [
      {
        phase_id: "PH1",
        phase_name: "Phase 1 — Core Build",
        modeled_primary_load_mw: 200,
        optional_expansion_mw: null,
        target_energization_date: "2026-06-01",
        status: "construction",
        utility: "Dominion Energy",
        interconnection_status_known: true,
        new_transmission_required: false,
      },
      {
        phase_id: "PH2",
        phase_name: "Phase 2 — Scale",
        modeled_primary_load_mw: 200,
        optional_expansion_mw: null,
        target_energization_date: "2026-12-01",
        status: "permitting",
        utility: "Dominion Energy",
        interconnection_status_known: true,
        new_transmission_required: false,
      },
      {
        phase_id: "PH3",
        phase_name: "Phase 3 — Densification",
        modeled_primary_load_mw: 120,
        optional_expansion_mw: null,
        target_energization_date: "2027-06-01",
        status: "planning",
        utility: "Dominion Energy",
        interconnection_status_known: false,
        new_transmission_required: false,
      },
      {
        phase_id: "PH4",
        phase_name: "Phase 4 — Final Wing",
        modeled_primary_load_mw: 100,
        optional_expansion_mw: null,
        target_energization_date: "2027-12-01",
        status: "planning",
        utility: null,
        interconnection_status_known: false,
        new_transmission_required: false,
      },
    ],
    score: {
      project_id: "P003",
      phase_id: null,
      current_hazard: 0.03,
      deadline_probability: 0.09,
      project_stress_score: 0.22,
      regional_stress_score: 0.31,
      anomaly_score: 0.11,
      evidence_quality_score: 0.91,
      top_drivers: [
        "High evidence quality reduces uncertainty",
        "PJM region moderate backlog",
      ],
      weak_signal_summary: "No E2/E3/E4 signals detected in trailing 4 quarters.",
      graph_fragility_summary: {
        most_likely_break_node: "none_identified",
        unresolved_critical_nodes: 0,
      },
      as_of_quarter: "2026-Q1",
    },
  },
  P004: {
    project_id: "P004",
    project_name: "Great Lakes Exchange",
    state: "OH",
    region_or_rto: "PJM",
    utility: "AEP Ohio",
    modeled_primary_load_mw: 310,
    headline_load_mw: 350,
    optional_expansion_mw: 80,
    lifecycle_state: "monitoring_ready",
    risk_tier: "high",
    announce_date: "2025-05-20",
    data_quality_score: 55,
    latest_update_date: "2026-02-20",
    phases: [
      {
        phase_id: "PH1",
        phase_name: "Phase 1",
        modeled_primary_load_mw: 160,
        optional_expansion_mw: 40,
        target_energization_date: "2026-10-01",
        status: "planning",
        utility: "AEP Ohio",
        interconnection_status_known: false,
        new_transmission_required: true,
      },
      {
        phase_id: "PH2",
        phase_name: "Phase 2",
        modeled_primary_load_mw: 150,
        optional_expansion_mw: 40,
        target_energization_date: "2027-06-01",
        status: "planning",
        utility: null,
        interconnection_status_known: false,
        new_transmission_required: true,
      },
    ],
    score: {
      project_id: "P004",
      phase_id: "PH1",
      current_hazard: 0.12,
      deadline_probability: 0.35,
      project_stress_score: 0.71,
      regional_stress_score: 0.49,
      anomaly_score: 0.52,
      evidence_quality_score: 0.55,
      top_drivers: [
        "Interconnection status unknown for both phases",
        "New transmission required — path unresolved",
        "Low evidence coverage (official updates: 1 trailing 2Q)",
        "High anomaly score vs peer projects in PJM",
      ],
      weak_signal_summary:
        "Three E2 signals detected. One E3 utility action signal (AEP Ohio large-load treatment update). Two E4 workaround indicators (behind-the-meter strategy reported).",
      graph_fragility_summary: {
        most_likely_break_node: "interconnection_queue",
        unresolved_critical_nodes: 4,
      },
      as_of_quarter: "2026-Q1",
    },
  },
  P005: {
    project_id: "P005",
    project_name: "Cascade Ridge AI Cluster",
    state: "WA",
    region_or_rto: "WECC",
    utility: "Puget Sound Energy",
    modeled_primary_load_mw: 800,
    headline_load_mw: 850,
    optional_expansion_mw: 300,
    lifecycle_state: "under_review",
    risk_tier: "elevated",
    announce_date: "2025-10-15",
    data_quality_score: 74,
    latest_update_date: "2026-03-28",
    phases: [
      {
        phase_id: "PH1",
        phase_name: "Phase 1",
        modeled_primary_load_mw: 200,
        optional_expansion_mw: 60,
        target_energization_date: "2026-12-01",
        status: "permitting",
        utility: "Puget Sound Energy",
        interconnection_status_known: true,
        new_transmission_required: false,
      },
      {
        phase_id: "PH2",
        phase_name: "Phase 2",
        modeled_primary_load_mw: 200,
        optional_expansion_mw: 60,
        target_energization_date: "2027-06-01",
        status: "planning",
        utility: "Puget Sound Energy",
        interconnection_status_known: false,
        new_transmission_required: false,
      },
      {
        phase_id: "PH3",
        phase_name: "Phase 3",
        modeled_primary_load_mw: 200,
        optional_expansion_mw: 90,
        target_energization_date: "2027-12-01",
        status: "planning",
        utility: null,
        interconnection_status_known: false,
        new_transmission_required: true,
      },
      {
        phase_id: "PH4",
        phase_name: "Phase 4",
        modeled_primary_load_mw: 100,
        optional_expansion_mw: 45,
        target_energization_date: "2028-06-01",
        status: "planning",
        utility: null,
        interconnection_status_known: false,
        new_transmission_required: true,
      },
      {
        phase_id: "PH5",
        phase_name: "Phase 5 (Expansion)",
        modeled_primary_load_mw: 100,
        optional_expansion_mw: 45,
        target_energization_date: "2028-12-01",
        status: "planning",
        utility: null,
        interconnection_status_known: false,
        new_transmission_required: false,
      },
    ],
    score: {
      project_id: "P005",
      phase_id: null,
      current_hazard: 0.06,
      deadline_probability: 0.19,
      project_stress_score: 0.48,
      regional_stress_score: 0.41,
      anomaly_score: 0.27,
      evidence_quality_score: 0.74,
      top_drivers: [
        "Transmission dependency in phases 3–4",
        "Large optional expansion increases uncertainty",
        "Phased energization adds complexity",
      ],
      weak_signal_summary:
        "One E2 signal (phase 2 permitting delay reported by developer). One E4 indicator (staged energization architecture).",
      graph_fragility_summary: {
        most_likely_break_node: "transmission_upgrade",
        unresolved_critical_nodes: 2,
      },
      as_of_quarter: "2026-Q1",
    },
  },
  P006: {
    project_id: "P006",
    project_name: "Sunbelt Compute Park",
    state: "GA",
    region_or_rto: "SERC",
    utility: "Georgia Power",
    modeled_primary_load_mw: 400,
    headline_load_mw: 420,
    optional_expansion_mw: 100,
    lifecycle_state: "delayed",
    risk_tier: "high",
    announce_date: "2025-03-01",
    data_quality_score: 68,
    latest_update_date: "2026-01-10",
    phases: [
      {
        phase_id: "PH1",
        phase_name: "Phase 1",
        modeled_primary_load_mw: 200,
        optional_expansion_mw: 50,
        target_energization_date: "2026-06-01",
        status: "delayed",
        utility: "Georgia Power",
        interconnection_status_known: true,
        new_transmission_required: true,
      },
      {
        phase_id: "PH2",
        phase_name: "Phase 2",
        modeled_primary_load_mw: 200,
        optional_expansion_mw: 50,
        target_energization_date: "2027-01-01",
        status: "planning",
        utility: "Georgia Power",
        interconnection_status_known: false,
        new_transmission_required: true,
      },
    ],
    score: {
      project_id: "P006",
      phase_id: "PH1",
      current_hazard: 0.15,
      deadline_probability: 0.41,
      project_stress_score: 0.79,
      regional_stress_score: 0.55,
      anomaly_score: 0.61,
      evidence_quality_score: 0.68,
      top_drivers: [
        "Phase 1 already flagged as delayed",
        "Transmission upgrade bottleneck confirmed",
        "Georgia Power substation upgrade under review",
        "High anomaly score vs SERC peers",
      ],
      weak_signal_summary:
        "Four E2 signals (confirmed timeline slippage with power-constraint mention). Two E3 signals (SERC large-load policy action). One E4 indicator (behind-the-meter alternative evaluated).",
      graph_fragility_summary: {
        most_likely_break_node: "transmission_upgrade",
        unresolved_critical_nodes: 5,
      },
      as_of_quarter: "2026-Q1",
    },
  },
  P007: {
    project_id: "P007",
    project_name: "Northern Plains Hub",
    state: "ND",
    region_or_rto: "MISO",
    utility: "Basin Electric",
    modeled_primary_load_mw: 350,
    headline_load_mw: 350,
    optional_expansion_mw: null,
    lifecycle_state: "monitoring_ready",
    risk_tier: "low",
    announce_date: "2025-08-10",
    data_quality_score: 88,
    latest_update_date: "2026-04-02",
    phases: [
      {
        phase_id: "PH1",
        phase_name: "Phase 1",
        modeled_primary_load_mw: 350,
        optional_expansion_mw: null,
        target_energization_date: "2027-01-01",
        status: "permitting",
        utility: "Basin Electric",
        interconnection_status_known: true,
        new_transmission_required: false,
      },
    ],
    score: {
      project_id: "P007",
      phase_id: "PH1",
      current_hazard: 0.02,
      deadline_probability: 0.06,
      project_stress_score: 0.14,
      regional_stress_score: 0.22,
      anomaly_score: 0.09,
      evidence_quality_score: 0.88,
      top_drivers: [
        "Strong evidence quality",
        "MISO region low stress",
        "No transmission dependency",
      ],
      weak_signal_summary: "No E2/E3/E4 signals in trailing 4 quarters.",
      graph_fragility_summary: {
        most_likely_break_node: "none_identified",
        unresolved_critical_nodes: 0,
      },
      as_of_quarter: "2026-Q1",
    },
  },
};

export const MOCK_TIMELINES: Record<string, TimelineEvent[]> = {
  P001: [
    {
      date: "2025-07-15",
      source_type: "county_record",
      summary: "Project announced with 300 MW initial build in Travis County.",
    },
    {
      date: "2025-10-01",
      source_type: "county_record",
      summary: "Site permits filed. Phase 1 timeline confirmed Q3 2026.",
    },
    {
      date: "2026-02-15",
      source_type: "utility_statement",
      summary: "Oncor confirms substation and transmission upgrades under review.",
    },
    {
      date: "2026-04-01",
      source_type: "regulatory_filing",
      summary:
        "ERCOT interconnection application submitted. New transmission line required for full Phase 1 load.",
    },
  ],
  P004: [
    {
      date: "2025-05-20",
      source_type: "press",
      summary: "Project announced, 310 MW, two phases, AEP Ohio territory.",
    },
    {
      date: "2025-11-03",
      source_type: "developer_statement",
      summary:
        "Developer confirms behind-the-meter generation under evaluation as backup path.",
    },
    {
      date: "2026-01-18",
      source_type: "utility_statement",
      summary:
        "AEP Ohio signals updated large-load treatment policy for new interconnection requests.",
    },
    {
      date: "2026-02-20",
      source_type: "press",
      summary:
        "No public update on interconnection status. Analyst flag: stale data.",
    },
  ],
};
